### ISSUE TITLE
prune... what is happening

### ISSUE THREAD

**Issue by valentinedwv** [fils/nabu#26]
pruning with orgs looking for orgs in summmon/org?

and urn pattern looks broken:
Pattern: urn:gleanermilled/iris:
Graph items: 0  Object items: 28  difference: 0
Missing item count: 28
{"Graph items":0,"Missing item count":28,"Object items":28,"difference":0,"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphprune.go:67","func":"github.com/gleanerio/nabu/internal/prune.Snip","level":"info","msg":"Nabu Prune","prefix":"milled/iris","time":"2023-02-10T14:56:24-08:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphprune.go:87","func":"github.com/gleanerio/nabu/internal/prune.Snip","level":"info","msg":"uploading missing %n objects28","time":"2023-02-10T14:56:24-08:00"}
 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (28/28, 1 it/s)         
Exiting.

```
minio:
    address: oss.geocodes.ncsa.illinois.edu
    port: 443
    ssl: true
    accesskey: accesskey
    secretkey: secretkey
    bucket: gleaner
objects:
    bucket: gleaner
    domain: us-east-1
    prefix:
        - summoned/iris
        - org
    prefixoff: []
sparql:
    endpoint: https://graph.geocodes.ncsa.illinois.edu/blazegraph/namespace/iris_nabu/sparql
    authenticate: false
    username: ""
    password: ""
txtaipkg:
    endpoint: http://0.0.0.0:8000
```

`nabu prune --cfg ../gleaner/configs/summarize/nabu --prefix orgs --prefix milled/iris`

or

`nabu prune --cfg ../gleaner/configs/summarize/nabu --prefix org --prefix milled/iris`

``` 
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/objectlist.go:44","func":"github.com/gleanerio/nabu/internal/prune.ObjectList","level":"info","msg":"gleaner:orgs object count: 10\n","time":"2023-02-10T14:49:35-08:00"}
Pattern: urn:gleanerorgs:
Graph items: 0  Object items: 10  difference: 0
Missing item count: 10
{"Graph items":0,"Missing item count":10,"Object items":10,"difference":0,"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphprune.go:67","func":"github.com/gleanerio/nabu/internal/prune.Snip","level":"info","msg":"Nabu Prune","prefix":"orgs","time":"2023-02-10T14:49:35-08:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphprune.go:87","func":"github.com/gleanerio/nabu/internal/prune.Snip","level":"info","msg":"uploading missing %n objects10","time":"2023-02-10T14:49:35-08:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/objects/gets3bytes.go:21","func":"github.com/gleanerio/nabu/internal/objects.GetS3Bytes","level":"info","msg":"Issue with reading an object:  gleaner/summoned/orgs/aquadocs.jsonld","time":"2023-02-10T14:49:35-08:00"}
```
