### ISSUE TITLE
release failing

### ISSUE THREAD

**Issue by valentinedwv** [fils/nabu#35]
Failed to create a release.
And I think if one release fails, any additional releases do not get generated.

```
@geocodes:~/indexing$ ./glcon nabu release --cfgName aws_geocodes
Using nabu config file: /home/ubuntu/indexing/configs/aws_geocodes/nabu
nabu release called

2023/05/13 13:07:20 Error decoding triples: syntax error: bad IRI: disallowed character ' '

```

files in opencore on oss.geocodes-dev.earthcube.org
org is empty.

```
GOROOT=/usr/local/opt/go/libexec #gosetup
GOPATH=/Users/valentin/go #gosetup
/usr/local/opt/go/libexec/bin/go build -ldflags -X main.VERSION=testline -o /private/var/folders/t2/t39bprkn16dg9nr4v6c18v0w0000gn/T/GoLand/___nabu_release_opencore /Users/valentin/development/dev_earthcube/gleanerio/gleaner/cmd/glcon/main.go #gosetup
/private/var/folders/t2/t39bprkn16dg9nr4v6c18v0w0000gn/T/GoLand/___nabu_release_opencore nabu release --cfg configs/opencore_nabu
Using nabu config file: configs/opencore_nabu
nabu release called
2023/05/03 07:06:22 Error decoding triples: 1:195 unexpected 3 as dot (.)

Process finished with the exit code 0
```

```
minio:
    address: oss.geocodes-dev.earthcube.org
    port: 443
    ssl: true
    accesskey:
    secretkey:
    bucket: opencore
objects:
    bucket: opencore
    domain: us-west-2
    prefix:
        - summoned/opencoredata
        - org
    prefixoff: []
sparql:
    endpoint: https://graph.geocodes-dev.earthcube.org/blazegraph/namespace/opencore/sparql
    authenticate: false
    username: ""
    password: ""
txtaipkg:
    endpoint: http://0.0.0.0:800
```
