### ISSUE TITLE
prune Bad endpoint, still runs

### ISSUE THREAD

**Issue by valentinedwv** [fils/nabu#53]
checking to see if passing sparql endpoint still worked.
fed it a bad sparql endpoint, still ran... in fact it acts like prune query worked 

`SPARQL: SELECT DISTINCT ?g WHERE {GRAPH ?g {?s ?p ?o} `

endpoint
```
endpoints:
  - service: ec_blazegraph
    baseurl: https://graph.geocodes-aws-dev.earthcube.org/blazegraph/namespace/blah
    type: blazegraph
    authenticate: false
    username: admin
    password: jfpwd
    modes:
      - action: sparql
        suffix: /sparql
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /sparql
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /sparql
        accept: text/x-nquads
        method: POST
```

```
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/objects/objectlist.go:44","func":"github.com/gleanerio/nabu/internal/objects.ObjectList","level":"info","msg":"test:summoned/geocodes_demo_datasets object count: 18\n","time":"2023-10-05T10:34:38-07:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphList.go:18","func":"github.com/gleanerio/nabu/internal/prune.graphList","level":"info","msg":"Getting list of named graphs","time":"2023-10-05T10:34:38-07:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphList.go:44","func":"github.com/gleanerio/nabu/internal/prune.graphList","level":"info","msg":"Pattern: urn:gleaner.io:TEST:geocodes_demo_datasets:data\n","time":"2023-10-05T10:34:38-07:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphList.go:45","func":"github.com/gleanerio/nabu/internal/prune.graphList","level":"info","msg":"SPARQL: SELECT DISTINCT ?g WHERE {GRAPH ?g {?s ?p ?o} }\n","time":"2023-10-05T10:34:38-07:00"}
Current graph items: 0  Cuurent object items: 18
Orphaned items to remove: 0
Missing items to add: 18
{"difference":0,"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphprune.go:73","func":"github.com/gleanerio/nabu/internal/prune.Snip","graph items":0,"level":"info","missing":18,"msg":"Nabu Prune","object items":18,"prefix":"summoned/geocodes_demo_datasets","time":"2023-10-05T10:34:38-07:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/prune/graphprune.go:105","func":"github.com/gleanerio/nabu/internal/prune.Snip","level":"info","msg":"uploading missing %n objects18","time":"2023-10-05T10:34:38-07:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/graph/insert.go:47","func":"github.com/gleanerio/nabu/internal/graph.Insert","level":"info","msg":"response Status: 404 Not Found","time":"2023-10-05T10:34:38-07:00"}
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/graph/insert.go:48","func":"github.com/gleanerio/nabu/internal/graph.Insert","level":"info","msg":"response Headers: map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Headers:[Authorization,Origin,Content-Type,Accept] Access-Control-Allow-Origin:[*] Content-Type:[text/plain] Date:[Thu, 05 Oct 2023 17:34:39 GMT] Server:[Jetty(9.4.z-SNAPSHOT)] Vary:[Origin] X-Frame-Options:[SAMEORIGIN]]","time":"2023-10-05T10:34:38-07:00"}
   5% |██████                     
```
